Vagrant.configure("2") do |config|
  config.vm.box = "centos65"
  #Uncomment if using a local proxy like CNTLM
  #config.proxy.http     = "http://10.132.200.175:3128"
  #config.proxy.https    = "http://10.132.200.175:3128"

  config.vm.define :box1 do |box1|
    box1.vm.network :private_network, :ip => "192.168.43.10"
    box1.vm.hostname = "box1"
    box1.vm.synced_folder ENV['HOME'], "/home/vagrant/home"
    box1.vm.provider "virtualbox" do |v|
      v.customize ['modifyvm', :id, '--memory', '4096']
      v.customize ['modifyvm', :id, '--cpus', '2']
    end
  end
end
